import Toy from "../models/toy";

// title: mix
// id:0
// title: "Girls",
// id: 1,

// title: "Boys",
// id: 2,

// title: "Action figures",
// id: 3,

// title: "Animals",
// id: 4,

// title: "Cars and RC",
// id: 5,

// title: "Creative toys",
// id: 6,

// title: "Dolls",
// id: 7,

// title: "Games",
// id: 8,

// title: "Wooden toys",
// id: 9,

const toys: Toy[] = [
  {
    id: 0,
    name: "Car Transport Truck",
    img: "car_transport_truck.jpeg",
    price: 29.99,
    sectionId: 9,
    gender: 2,
  },
  {
    id: 1,
    name: "Ninja Turtles-Leonardo",
    img: "turtle.jpeg",
    price: 14.99,
    sectionId: 3,
    gender: 2,
  },
  {
    id: 2,
    name: "Terminator",
    img: "terminator.jpeg",
    price: 18.99,
    sectionId: 3,
    gender: 2,
  },
  {
    id: 3,
    name: "Jack Sparrow",
    img: "sparrow.jpeg",
    price: 21.99,
    sectionId: 3,
    gender: 2,
  },
  {
    id: 4,
    name: "Schleich",
    img: "schleich.jpeg",
    price: 9.99,
    sectionId: 3,
    gender: 1,
  },
  {
    id: 5,
    name: "Nun",
    img: "nun.jpeg",
    price: 17.99,
    sectionId: 3,
    gender: 0,
  },
  {
    id: 6,
    name: "Aerith",
    img: "aerith.jpeg",
    price: 22.99,
    sectionId: 3,
    gender: 1,
  },
  {
    id: 7,
    name: "Lock, Shock and Barrel",
    img: "nightmare.jpeg",
    price: 11.99,
    sectionId: 3,
    gender: 0,
  },
  {
    id: 8,
    name: "Patrick",
    img: "patrick.jpeg",
    price: 18.99,
    sectionId: 3,
    gender: 0,
  },
  {
    id: 9,
    name: "Simba",
    img: "simba.jpeg",
    price: 9.99,
    sectionId: 4,
    gender: 1,
  },
  {
    id: 10,
    name: "Farm",
    img: "farm.jpeg",
    price: 29.99,
    sectionId: 4,
    gender: 0,
  },
  {
    id: 11,
    name: "Tiger",
    img: "tiger.jpeg",
    price: 39.99,
    sectionId: 4,
    gender: 2,
  },
  {
    id: 12,
    name: "Komodo Dragon",
    img: "komodo.jpeg",
    price: 39.99,
    sectionId: 4,
    gender: 2,
  },
  {
    id: 13,
    name: "RC Dump Truck",
    img: "rc_dump_truck.jpeg",
    price: 59.99,
    sectionId: 5,
    gender: 2,
  },
  {
    id: 14,
    name: "RC Helicopter",
    img: "heli.jpeg",
    price: 9.99,
    sectionId: 5,
    gender: 2,
  },
  {
    id: 15,
    name: "RC Car",
    img: "car.jpeg",
    price: 6.99,
    sectionId: 5,
    gender: 2,
  },
  {
    id: 16,
    name: "RC Car",
    img: "car2.jpeg",
    price: 7.99,
    sectionId: 5,
    gender: 2,
  },
  {
    id: 17,
    name: "RC Drone",
    img: "drone.jpeg",
    price: 17.99,
    sectionId: 5,
    gender: 0,
  },
  {
    id: 18,
    name: "RC Exost",
    img: "exost.jpeg",
    price: 26.05,
    sectionId: 5,
    gender: 2,
  },
  {
    id: 19,
    name: "RC Ycoo Robot",
    img: "yco.jpeg",
    price: 38.85,
    sectionId: 5,
    gender: 0,
  },
  {
    id: 20,
    name: "Lego Big Box",
    img: "lego.jpeg",
    price: 47.15,
    sectionId: 6,
    gender: 0,
  },
  {
    id: 21,
    name: "Star Wars Lego",
    img: "starwars.jpeg",
    price: 17.99,
    sectionId: 6,
    gender: 2,
  },
  {
    id: 22,
    name: "City Hair Salon Lego",
    img: "hairsalon.jpeg",
    price: 14.99,
    sectionId: 6,
    gender: 1,
  },
  {
    id: 23,
    name: "Barbie 1 piece",
    img: "barbies.jpeg",
    price: 8.99,
    sectionId: 7,
    gender: 1,
  },
  {
    id: 24,
    name: "L.O.L. 3 pieces",
    img: "lol.jpeg",
    price: 18.69,
    sectionId: 7,
    gender: 1,
  },

  {
    id: 25,
    name: "Wee Baby",
    img: "wee.jpeg",
    price: 31.59,
    sectionId: 7,
    gender: 1,
  },
  {
    id: 26,
    name: "Uno",
    img: "uno.jpg",
    price: 0.99,
    sectionId: 8,
    gender: 0,
  },
  {
    id: 27,
    name: "Monopoly",
    img: "monopoly.jpeg",
    price: 28.99,
    sectionId: 8,
    gender: 0,
  },
  {
    id: 28,
    name: "Risk",
    img: "risk.jpeg",
    price: 43.15,
    sectionId: 8,
    gender: 0,
  },
  {
    id: 29,
    name: "Scrabble",
    img: "scrabble.jpeg",
    price: 17.8,
    sectionId: 8,
    gender: 0,
  },
  {
    id: 30,
    name: "YU-GI-OH",
    img: "yu.jpeg",
    price: 53.5,
    sectionId: 8,
    gender: 2,
  },
  {
    id: 31,
    name: "Blocks",
    img: "blocks.jpeg",
    price: 11.2,
    sectionId: 9,
    gender: 0,
  },
  {
    id: 32,
    name: "Bicycle",
    img: "bicycle.jpeg",
    price: 70,
    sectionId: 9,
    gender: 0,
  },
  {
    id: 33,
    name: "Escavator",
    img: "escavator.jpeg",
    price: 15.65,
    sectionId: 9,
    gender: 2,
  },
  {
    id: 34,
    name: "Kitchen",
    img: "kitchen.jpeg",
    price: 27.6,
    sectionId: 9,
    gender: 1,
  },
  {
    id: 35,
    name: "House",
    img: "house.jpeg",
    price: 85.99,
    sectionId: 9,
    gender: 1,
  },
  {
    id: 36,
    name: "Ambulance",
    img: "ambulance.jpeg",
    price: 15.8,
    sectionId: 9,
    gender: 2,
  },
];

export default toys;
